import { Link } from 'react-router-dom';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { useLibrary } from '@/hooks/useStories';
import { BookOpen } from 'lucide-react';

const About = () => {
  const { stories } = useLibrary();

  return (
    <div className="min-h-screen bg-background">
      <Header stories={stories} showSearch={false} />

      <main className="px-4 md:px-12 py-12 max-w-2xl mx-auto">
        <h1 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-8">
          What is PagePortals?
        </h1>

        <div className="prose prose-invert prose-lg max-w-none space-y-6 text-muted-foreground leading-relaxed">
          <p>
            PagePortals is an experiment in artificial imagination. Every story in this library — from the plot to the prose to the cover art — was generated by AI. No human wrote these words. No human painted these covers.
          </p>
          <p>
            The question we're exploring: can a machine dream up something worth reading? Can it find emotion, tension, surprise? Can artificial minds create art that moves real ones?
          </p>
          <p>
            Browse the library and decide for yourself. Some stories are raw. Some are polished. All of them came from the same place — the strange, unpredictable space where language models meet storytelling.
          </p>
          <p>
            This is a living library. New stories appear as the machine dreams them up. Each novella is also a seed — a script waiting to become a film when AI video catches up to AI text. Every story you read today could be a movie tomorrow.
          </p>
        </div>

        <div className="mt-10">
          <Link
            to="/browse"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-colors shadow-lg"
          >
            <BookOpen size={18} />
            Start Reading
          </Link>
        </div>
      </main>

      <Footer storyCount={stories.length} />
    </div>
  );
};

export default About;
